{
 "title": "Homelab thermal and power use",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Homelab cooling flow",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 27, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": {
    "content": "graph TD    \nAMBIENT -- Main air intake --> rack_fan([Homelab Rack Fan]) -- Airflow to PVE --> pvenct6776_systin_input\nrack_fan -- Airflow to PVE --> pvesdb\nsubgraph APC UPS\n    apcload_electric_w[APC Load] == AC power === apcload_electric_v[APC Input]\nend\nsubgraph PVE \n    pvenct6776_systin_input[PVE Chassis] -. Airflow within PVE .-> pve_cpu_fan([PVE CPU Fan Speed]) -. Airflow within PVE .-> pvecoretemp_packageid0_input[PVE CPU Temperature]  -.- cpu_pve[PVE CPU Usage] -- UPS power --- apcload_electric_w\n    pvesdb[PVE HDD Temperature] -.- io_pve[PVE IO Wait]\nend\nrack_fan -- Airflow to PVE-LITE --> pve-litecoretemp_packageid0_input\nrack_fan -- Airflow to PVE-LITE --> pve-litesda\nsubgraph PVE-LITE\n    pve-litecoretemp_packageid0_input[PVE-LITE CPU Temperature] -.- cpu_pve-lite[PVE-LITE CPU Usage]  -- UPS power----- apcload_electric_w\n    pve-litesda[PVE-LITE HDD Temperature] -.- io_pve-lite[PVE-LITE IO Wait]\nend\nrack_fan -- Airflow to Arbiter--> arbitersoc_thermal_input[ArbiterCPU Temperature] \nsubgraph Arbiter\n    arbitersoc_thermal_input -.- cpu_arbiter[Arbiter CPU Usage]  -- UPS power ----- apcload_electric_w\nend"
   },
   "targets": [
    {
     "alias": "AMBIENT",
     "measurement": "°C",
     "query": "SELECT \"value\" FROM \"autogen\".\"°C\" WHERE (\"entity_id\" = 'pve_cpu_temperature') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "entrance_door_sensor_air_temperature"
      }
     ]
    },
    {
     "alias": "cpu_$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "io_$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "wait" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "cpu_arbiter",
     "measurement": "cpu",
     "query": "SELECT \"usage_idle\"*-0.01+1 FROM \"cpu\" WHERE (\"host\" = 'arbiter') AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nexbox" }
     ]
    },
    {
     "alias": "$tag_host$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temp\" FROM \"autogen\".\"temp\" WHERE ((\"sensor\" =~ /.input/ AND \"sensor\" !~ /.pch/ AND \"sensor\" !~ /.auxtin/ AND \"sensor\" !=  'acpitz_input') OR \"sensor\" = 'soc_thermal') AND $timeFilter GROUP BY \"host\", \"sensor\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temp_c\" FROM \"smart_device\" WHERE $timeFilter GROUP BY \"host\", \"device\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "pve_cpu_fan",
     "measurement": "pve_cpu_fan",
     "query": "SELECT mean(\"fanspeed\") FROM \"pve_cpu_fan\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "fanspeed" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "rack_fan",
     "measurement": "rack_fan",
     "query": "SELECT last(\"fanspeed\") FROM \"rack_fan\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "fanspeed" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "apcload_electric_w",
     "measurement": "apcupsd",
     "query": "SELECT (\"nominal_power\" * \"load_percent\") /100 FROM \"apcupsd\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "nominal_power" ], "type": "field" }
      ],
      [
       { "params": [ "load_percent" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "apcload_electric_v",
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Homelab Fan Speeds (rpm) - Last 24 hours",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "alias": "Homelab Rack Fan",
     "measurement": "rack_fan",
     "query": "SELECT mean(\"fanspeed\") FROM \"rack_fan\",\"pve_cpu_fan\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fanspeed" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PVE CPU Fan",
     "measurement": "pve_cpu_fan",
     "query": "SELECT mean(\"fanspeed\") FROM \"rack_fan\",\"pve_cpu_fan\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fanspeed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "APC Battery Electrical Load - Last 24 hours",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Electrical Load",
     "measurement": "apcupsd",
     "query": "SELECT (\"nominal_power\"* \"load_percent\")/100 FROM \"autogen\".\"apcupsd\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "nominal_power" ], "type": "field" }
      ],
      [
       { "params": [ "load_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "APC Battery Charge and Load - Last 24 hours",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" }
      ],
      [
       { "params": [ "load_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "APC  Input Voltage (V) - Last 24 hours",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures - Last 24 hours",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "AMBIENT",
     "measurement": "°C",
     "query": "SELECT \"value\" FROM \"autogen\".\"°C\" WHERE (\"entity_id\" = 'pve_cpu_temperature') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "entrance_door_sensor_air_temperature"
      }
     ]
    },
    {
     "alias": "$tag_host $tag_sensor",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "temp",
     "query": "SELECT \"temp\" FROM \"autogen\".\"temp\" WHERE ((\"sensor\" =~ /.input/ AND \"sensor\" !~ /.pch/ AND \"sensor\" !~ /.auxtin/ AND \"sensor\" !=  'acpitz_input') OR \"sensor\" = 'soc_thermal') AND $timeFilter GROUP BY \"host\", \"sensor\"",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/.input/" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "soc_thermal" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "$tag_host $tag_device",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "query": "SELECT \"temp_c\" FROM \"smart_device\" WHERE $timeFilter GROUP BY \"host\", \"device\"",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}