{
 "title": "Homelab overview",
 "description": "Display data from  Proxmox hosts, Qdevice node,  Guest machines, and environmental measurements.",
 "tags": [
  "proxmox",
  "homelab",
  "qemu",
  "lxc"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "PVE Host Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" }
     ]
    }
   ]
  },
  {
   "title": "PVE Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" }
     ]
    }
   ]
  },
  {
   "title": "PVE Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" }
     ]
    }
   ]
  },
  {
   "title": "PVE I/O Wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "wait" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" }
     ]
    }
   ]
  },
  {
   "title": "PVE Cluster Load Averages (1 Minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PVE",
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "avg1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" }
     ]
    },
    {
     "alias": "PVE-LITE",
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "avg1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" }
     ]
    }
   ]
  },
  {
   "title": "Arbiter Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "arbiter" }
     ]
    }
   ]
  },
  {
   "title": "Arbiter CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "cpu",
     "query": "SELECT (\"usage_idle\" -100)*-1 FROM \"cpu\" WHERE (\"host\" = 'arbiter') AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ "-100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nexbox" }
     ]
    }
   ]
  },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PVE Guests",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(uptime) AS \"uptime\" FROM \"system\" WHERE ((\"object\" = 'lxc') OR (\"object\" = 'qemu')) AND (\"nodename\" = 'pve') AND time > (now() - 10m) AND uptime > 0 GROUP BY \"host\" limit 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       { "params": [ "uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  {
   "title": "PVE CPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" }
     ]
    }
   ]
  },
  {
   "title": "PVE Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" }
     ]
    }
   ]
  },
  {
   "title": "PVE Storage Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"used\")/last(\"total\") FROM \"system\" WHERE (\"nodename\" = 'pve') AND $timeFilter GROUP BY \"nodename\", \"host\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Homelab Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "ambient sensor",
     "measurement": "°C",
     "query": "SELECT \"value\" FROM \"autogen\".\"°C\" WHERE (\"entity_id\" = 'pve_cpu_temperature') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "entrance_door_sensor_air_temperature"
      }
     ]
    },
    {
     "alias": "$tag_host $tag_sensor",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "temp",
     "query": "SELECT \"temp\" FROM \"autogen\".\"temp\" WHERE ((\"sensor\" =~ /.input/ AND \"sensor\" !~ /.pch/ AND \"sensor\" !~ /.auxtin/ AND \"sensor\" !=  'acpitz_input' AND \"sensor\" !~ /._core/ AND \"sensor\" !~ /.skylake/ AND \"sensor\" !~ /.peciagent/) OR \"sensor\" = 'soc_thermal') AND $timeFilter GROUP BY \"host\", \"sensor\"",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/.input/" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "soc_thermal" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "$tag_host $tag_device",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "query": "SELECT \"temp_c\" FROM \"smart_device\" WHERE $timeFilter GROUP BY \"host\", \"device\"",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Homelab LAN Internet Access",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Speedtest",
     "query": "SELECT \"download_bandwidth\"*8, \"upload_bandwidth\"*8, \"ping_latency\" FROM \"Speedtest\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" }
      ],
      [
       { "params": [ "upload_bandwidth" ], "type": "field" }
      ],
      [
       { "params": [ "ping_latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PVE NICs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "WAN0 Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp3s0" }
     ]
    },
    {
     "alias": "WAN0 Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp3s0" }
     ]
    },
    {
     "alias": "LAN0 Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp0s31f6" }
     ]
    },
    {
     "alias": "LAN0 Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp0s31f6" }
     ]
    },
    {
     "alias": "DMZ0 Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmbr2" }
     ]
    },
    {
     "alias": "DMZ0 Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmbr2" }
     ]
    },
    {
     "alias": "2.5G Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enx002427880297" }
     ]
    },
    {
     "alias": "2.5G Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enx002427880297" }
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE Host Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" }
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" }
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" }
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE I/O Wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "wait" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" }
     ]
    }
   ]
  },
  {
   "title": "Network Latency (WAN, LAN, and Storage)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_url $col",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ],
      [
       { "params": [ "percent_packet_loss" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Homlab Cooling",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "alias": "Homelab Rack Fan",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "rack_fan",
     "select": [
      [
       { "params": [ "fanspeed" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PVE CPU Fan",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "pve_cpu_fan",
     "select": [
      [
       { "params": [ "fanspeed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE Guests",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(uptime) AS \"uptime\" FROM \"system\" WHERE ((\"object\" = 'lxc') OR (\"object\" = 'qemu')) AND (\"nodename\" = 'pve-lite') AND time > (now() - 10m) AND uptime > 0 GROUP BY \"host\" limit 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       { "params": [ "uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE CPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" }
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" }
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE Storage Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"used\")/last(\"total\") FROM \"system\" WHERE (\"nodename\" = 'pve-lite') AND $timeFilter GROUP BY \"nodename\", \"host\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "APC Battery Electrical Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Electrical Load",
     "measurement": "apcupsd",
     "query": "SELECT ((max(\"nominal_power\")* max(\"load_percent\"))/100) FROM \"autogen\".\"apcupsd\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "nominal_power" ], "type": "field" }
      ],
      [
       { "params": [ "load_percent" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT max(\"battery_charge_percent\") FROM \"apcupsd\" WHERE $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PVE-LITE NICs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "WAN0 Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enx000ec6fe015f" }
     ]
    },
    {
     "alias": "WAN0 Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enx000ec6fe015f" }
     ]
    },
    {
     "alias": "LAN0 Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1" }
     ]
    },
    {
     "alias": "LAN0 Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1" }
     ]
    },
    {
     "alias": "DMZ0 Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmbr2" }
     ]
    },
    {
     "alias": "DMZ0 Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmbr2" }
     ]
    },
    {
     "alias": "2.5G Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enxa0cec8c94da2" }
     ]
    },
    {
     "alias": "2.5G Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve-lite" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enxa0cec8c94da2" }
     ]
    }
   ]
  }
 ]
}